FROM python:alpine 

# run update
RUN apk update

# install reqs
WORKDIR /app
ADD src/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
ADD src /app

EXPOSE 5000 9090

CMD python app.py
